typography_spectrum: 0.6324769302736968
color:
  brandStrength: 0.7462601400911808
  lightness: 0.9954831141512841
  saturation: 0.4958609235472977
  rhythmicContrast: 0.44232993433251977
  brandColors:
    - '#225378'
    - '#1695A3'
    - '#ACF0F2'
    - '#F3FFE2'
    - '#EB7F00'
layout_spectrum: 0.6885627643205225
author:
  name: Jorge Garcia
  email: info@magothejack.com.ar
  url: www.magothejack.com.ar
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/081c0cb1-8543-48b2-9ad7-5f9825f19beb.png
name: the Jack
title: Artist - Entertainer - TED Speaker
description: Writer
